name: Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: PHP testing actions
        uses: 104lab/docker-lazy-php@main
        with:
          args: php -v && php -m
